export const languageMaps: string[] = [
  'Arabic (Egyptian)',
  'Arabic (Moroccan)',
  'Arabic (Modern Standard)',
  'Arabic (Sudanese)',
  'Bengali',
  'Burmese',
  'Chinese (Mandarin)',
  'Chinese (Wu/Shanghainese)',
  'Chinese (Yue/Cantonese)',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Filipino (Tagalog)',
  'Finnish',
  'French',
  'German',
  'Greek',
  'Hebrew',
  'Hindi',
  'Indonesian',
  'Italian',
  'Japanese',
  'Korean',
  'Malay',
  'Norwegian',
  'Persian (Iranian)',
  'Polish',
  'Portuguese',
  'Romanian',
  'Russian',
  'Spanish',
  'Swahili',
  'Swedish',
  'Tamil',
  'Thai',
  'Turkish',
  'Ukrainian',
  'Vietnamese'
];
