import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Download, Calendar, BarChart2, PieChart as PieChartIcon, LineChart as LineChartIcon, Users, CreditCard, RefreshCw } from "lucide-react";

export const adminUsers = [
  {
    id: 1,
    name: 'Maria Silva',
    email: 'maria@company.com',
    plan: 'Professional',
    credits: 85,
    status: 'active',
    lastActive: '2025-05-15',
    signupDate: '2025-01-10',
    billingStatus: 'paid',
  },
  {
    id: 2,
    name: 'João Oliveira',
    email: 'joao@business.com',
    plan: 'Essential',
    credits: 30,
    status: 'active',
    lastActive: '2025-05-14',
    signupDate: '2025-02-15',
    billingStatus: 'paid',
  },
  {
    id: 3,
    name: 'Ana Costa',
    email: 'ana@enterprise.com',
    plan: 'Completo',
    credits: 150,
    status: 'active',
    lastActive: '2025-05-13',
    signupDate: '2024-11-03',
    billingStatus: 'paid',
  },
  {
    id: 4,
    name: 'Carlos Santos',
    email: 'carlos@example.com',
    plan: 'Professional',
    credits: 12,
    status: 'warning',
    lastActive: '2025-05-12',
    signupDate: '2025-01-22',
    billingStatus: 'overdue',
  },
  {
    id: 5,
    name: 'Beatriz Lima',
    email: 'beatriz@company.net',
    plan: 'Essential',
    credits: 0,
    status: 'inactive',
    lastActive: '2025-05-01',
    signupDate: '2025-03-05',
    billingStatus: 'canceled',
  },
  {
    id: 6,
    name: 'Rafael Souza',
    email: 'rafael@startup.co',
    plan: 'Completo',
    credits: 172,
    status: 'active',
    lastActive: '2025-05-15',
    signupDate: '2024-10-12',
    billingStatus: 'paid',
  },
  {
    id: 7,
    name: 'Juliana Mendes',
    email: 'juliana@agency.com',
    plan: 'Professional',
    credits: 45,
    status: 'active',
    lastActive: '2025-05-10',
    signupDate: '2025-04-01',
    billingStatus: 'trial',
  },
  {
    id: 8,
    name: 'Fernando Almeida',
    email: 'fernando@consulting.org',
    plan: 'Essential',
    credits: 5,
    status: 'warning',
    lastActive: '2025-05-14',
    signupDate: '2025-02-28',
    billingStatus: 'paid',
  },
];

export const creditUsageData = [
  { name: 'Jan', usage: 4000 },
  { name: 'Feb', usage: 3000 },
  { name: 'Mar', usage: 5000 },
  { name: 'Apr', usage: 2780 },
  { name: 'May', usage: 1890 },
  { name: 'Jun', usage: 2390 },
  { name: 'Jul', usage: 3490 },
];

export const creditData = [
  { date: '05/12', earned: 350, used: 250 },
  { date: '05/13', earned: 420, used: 310 },
  { date: '05/14', earned: 380, used: 340 },
  { date: '05/15', earned: 490, used: 380 },
  { date: '05/16', earned: 520, used: 450 },
  { date: '05/17', earned: 400, used: 380 },
  { date: '05/18', earned: 450, used: 400 },
];

export const creditLogs = [
  {
    id: 1,
    date: '2025-05-18 14:23',
    user: 'Maria Silva',
    email: 'maria@company.com',
    type: 'used',
    amount: 5,
    details: 'Marketing Bot - WhatsApp Campaign',
    balance: 85,
  },
  {
    id: 2,
    date: '2025-05-18 10:45',
    user: 'João Oliveira',
    email: 'joao@business.com',
    type: 'used',
    amount: 8,
    details: 'Strategy Bot - Market Analysis',
    balance: 30,
  },
  {
    id: 3,
    date: '2025-05-17 16:12',
    user: 'Ana Costa',
    email: 'ana@enterprise.com',
    type: 'purchased',
    amount: 50,
    details: 'Extra Credit Purchase - Small Pack',
    balance: 150,
  },
  {
    id: 4,
    date: '2025-05-17 14:30',
    user: 'Carlos Santos',
    email: 'carlos@example.com',
    type: 'used',
    amount: 10,
    details: 'WhatsApp Bot - Customer Service',
    balance: 12,
  },
  {
    id: 5,
    date: '2025-05-17 09:15',
    user: 'Juliana Mendes',
    email: 'juliana@agency.com',
    type: 'allocated',
    amount: 150,
    details: 'Monthly Plan Renewal - Professional',
    balance: 180,
  },
  {
    id: 6,
    date: '2025-05-16 18:40',
    user: 'Fernando Almeida',
    email: 'fernando@consulting.org',
    type: 'used',
    amount: 15,
    details: 'Organization Bot - Task Management',
    balance: 5,
  },
  {
    id: 7,
    date: '2025-05-16 12:10',
    user: 'Rafael Souza',
    email: 'rafael@startup.co',
    type: 'used',
    amount: 8,
    details: 'Marketing Bot - Content Creation',
    balance: 172,
  },
  {
    id: 8,
    date: '2025-05-16 10:20',
    user: 'Beatriz Lima',
    email: 'beatriz@company.net',
    type: 'purchased',
    amount: 150,
    details: 'Extra Credit Purchase - Medium Pack',
    balance: 150,
  },
  {
    id: 9,
    date: '2025-05-15 15:30',
    user: 'Ana Costa',
    email: 'ana@enterprise.com',
    type: 'used',
    amount: 12,
    details: 'Strategic Planning - Competitive Analysis',
    balance: 100,
  },
  {
    id: 10,
    date: '2025-05-15 09:05',
    user: 'Maria Silva',
    email: 'maria@company.com',
    type: 'used',
    amount: 7,
    details: 'WhatsApp Bot - Automated Responses',
    balance: 90,
  },
];

export const subscriptions = [
  {
    id: 1,
    user: 'Maria Silva',
    email: 'maria@company.com',
    plan: 'Professional',
    amount: 'R$49.90',
    startDate: '2025-01-10',
    nextBilling: '2025-06-10',
    status: 'active',
    paymentMethod: 'Credit Card',
  },
  {
    id: 2,
    user: 'João Oliveira',
    email: 'joao@business.com',
    plan: 'Essential',
    amount: 'R$29.90',
    startDate: '2025-02-15',
    nextBilling: '2025-06-15',
    status: 'active',
    paymentMethod: 'Credit Card',
  },
  {
    id: 3,
    user: 'Ana Costa',
    email: 'ana@enterprise.com',
    plan: 'Completo',
    amount: 'R$59.90',
    startDate: '2024-11-03',
    nextBilling: '2025-06-03',
    status: 'active',
    paymentMethod: 'PayPal',
  },
  {
    id: 4,
    user: 'Carlos Santos',
    email: 'carlos@example.com',
    plan: 'Professional',
    amount: 'R$49.90',
    startDate: '2025-01-22',
    nextBilling: '2025-05-22',
    status: 'overdue',
    paymentMethod: 'Credit Card',
  },
  {
    id: 5,
    user: 'Beatriz Lima',
    email: 'beatriz@company.net',
    plan: 'Essential',
    amount: 'R$29.90',
    startDate: '2025-03-05',
    nextBilling: 'N/A',
    status: 'canceled',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 6,
    user: 'Rafael Souza',
    email: 'rafael@startup.co',
    plan: 'Completo',
    amount: 'R$59.90',
    startDate: '2024-10-12',
    nextBilling: '2025-06-12',
    status: 'active',
    paymentMethod: 'Credit Card',
  },
  {
    id: 7,
    user: 'Juliana Mendes',
    email: 'juliana@agency.com',
    plan: 'Professional',
    amount: 'R$0.00',
    startDate: '2025-05-01',
    nextBilling: '2025-06-01',
    status: 'trial',
    paymentMethod: 'N/A',
  },
];


///// Admin Reports
export const userActivityData = [
  { name: "Mon", active: 65, new: 4 },
  { name: "Tue", active: 59, new: 2 },
  { name: "Wed", active: 80, new: 3 },
  { name: "Thu", active: 81, new: 5 },
  { name: "Fri", active: 56, new: 3 },
  { name: "Sat", active: 55, new: 1 },
  { name: "Sun", active: 40, new: 0 },
];

export const revenueData = [
  { name: "Jan", revenue: 4000 },
  { name: "Feb", revenue: 3000 },
  { name: "Mar", revenue: 2000 },
  { name: "Apr", revenue: 2780 },
  { name: "May", revenue: 1890 },
];

export const agentUsageData = [
  { name: "Marketing Bot", usage: 4230 },
  { name: "WhatsApp Bot", usage: 3290 },
  { name: "Strategy Bot", usage: 2830 },
  { name: "Organization Bot", usage: 1520 },
  { name: "Customer Insights", usage: 960 },
];

export const availableReports = [
  {
    id: 1,
    name: "Monthly Financial Summary",
    description: "Revenue, expenses, and profit breakdown for the month",
    icon: <CreditCard className="h-5 w-5" />,
    format: "PDF",
  },
  {
    id: 2,
    name: "User Activity Report",
    description: "Detailed user engagement and activity metrics",
    icon: <Users className="h-5 w-5" />,
    format: "CSV, PDF",
  },
  {
    id: 3,
    name: "Agent Usage Analytics",
    description: "Usage breakdown by agent type and function",
    icon: <BarChart2 className="h-5 w-5" />,
    format: "PDF, XLSX",
  },
  {
    id: 4,
    name: "Subscription Trends",
    description: "Analysis of subscription patterns and churn rate",
    icon: <LineChartIcon className="h-5 w-5" />,
    format: "PDF",
  },
  {
    id: 5,
    name: "Credit Consumption Report",
    description: "Detailed breakdown of credit usage across platform",
    icon: <PieChartIcon className="h-5 w-5" />,
    format: "CSV, PDF",
  },
  {
    id: 6,
    name: "Custom Date Range Report",
    description: "Generate reports for specific time periods",
    icon: <Calendar className="h-5 w-5" />,
    format: "PDF, XLSX, CSV",
  },
];

// System stats
export const systemStats = [
  { name: "Total Users", value: "247", change: "+12%", isPositive: true },
  { name: "Active Subscriptions", value: "198", change: "+8%", isPositive: true },
  { name: "Monthly Revenue", value: "R$8,740", change: "+15%", isPositive: true },
  { name: "Churn Rate", value: "2.3%", change: "-0.5%", isPositive: true },
];